# Generated by Django 3.1.1 on 2020-09-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_router', '0003_auto_20200925_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdetails',
            name='ip_addr',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
