# Generated by Django 3.1.1 on 2020-09-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_router', '0004_auto_20200926_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerdetails',
            name='ip_addr',
        ),
    ]
