# Generated by Django 3.1.1 on 2020-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_router', '0005_remove_routerdetails_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='loopback',
            field=models.GenericIPAddressField(),
        ),
    ]
